### ISSUE TITLE
Error when yarn dev

### ISSUE THREAD

**Issue by Lejmassu** [dogancana/futbot#27]
Cant seem to start the server anymore with the new version? 
Did yarn and then yarn dev. 
I dont know anything about coding so I'm sorry if this isnt relatated to the script. 

Error: Invalid request-speed limit
    at Object.<anonymous> futbot-master\lib\api\fut-api\api.ts:21:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile \futbot-master\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] \futbot-master\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
error Command failed with exit code 1.

**Comment by dogancana** [comment]
There error is Invalid request-speed limit in your first line.
Make sure below line is present in your .env file

FUTBOT_FUT_REQUESTS_PER_SEC=.5

**Comment by dogancana** [comment]
I'm closing this issue as it's user error. 
And in current release, .env file values are verified and show proper error message.
